export const birthdayData = [
  {
    name: 'Luiz Eduardo',
    day: 24,
    sector: 'Suporte',
    location: 'João Pessoa',
    description:
      'Pariatur minus, unde dolorum omnis odit tempora hic velit harum, architecto in animi.',
    profilePic:
      'https://avatars.githubusercontent.com/u/110038345?u=c4645cc3fb2aa6faf5af612ef62ffb56ff13de32&v=4',
  },
  {
    name: 'Maria Clara',
    day: 15,
    sector: 'Financeiro',
    location: 'São Paulo',
    description: 'Atque quod harum soluta magnam minus. Exercitationem, fugit!',
    profilePic: 'https://randomuser.me/api/portraits/women/45.jpg',
  },
  {
    name: 'João Pedro',
    day: 30,
    sector: 'Desenvolvimento',
    location: 'Recife',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    profilePic: 'https://randomuser.me/api/portraits/men/33.jpg',
  },
  {
    name: 'Fernanda Souza',
    day: 5,
    sector: 'Recursos Humanos',
    location: 'Rio de Janeiro',
    description: 'Apaixonada por gestão de pessoas e café forte.',
    profilePic: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
  {
    name: 'Carlos Henrique',
    day: 18,
    sector: 'TI',
    location: 'Belo Horizonte',
    description:
      'Gamer nas horas vagas e especialista em segurança da informação.',
    profilePic: 'https://randomuser.me/api/portraits/men/50.jpg',
  },
  {
    name: 'Amanda Nogueira',
    day: 12,
    sector: 'Marketing',
    location: 'Fortaleza',
    description: 'Criativa e sempre antenada nas últimas tendências digitais.',
    profilePic: 'https://randomuser.me/api/portraits/women/32.jpg',
  },
  {
    name: 'Rafael Lima',
    day: 27,
    sector: 'Logística',
    location: 'Curitiba',
    description: 'Logística eficiente e otimização de processos são meu foco.',
    profilePic: 'https://randomuser.me/api/portraits/men/40.jpg',
  },
  {
    name: 'Juliana Mendes',
    day: 8,
    sector: 'Vendas',
    location: 'Salvador',
    description: 'Amante de metas e desafios. Cliente feliz é minha missão!',
    profilePic: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
  {
    name: 'Gabriel Oliveira',
    day: 22,
    sector: 'Suporte Técnico',
    location: 'Brasília',
    description: 'Resolver problemas e ajudar clientes é o que me move.',
    profilePic: 'https://randomuser.me/api/portraits/men/35.jpg',
  },
  {
    name: 'Beatriz Santos',
    day: 3,
    sector: 'Desenvolvimento',
    location: 'Florianópolis',
    description: 'Fullstack developer apaixonada por código limpo e inovação.',
    profilePic: 'https://randomuser.me/api/portraits/women/30.jpg',
  },
]
